//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHCL2018.Registrations.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MhclTeam
    {
        public MhclTeam()
        {
            this.MhclPlayer = new HashSet<MhclPlayer>();
        }
    
        public int TeamId { get; set; }
        public string TeamName { get; set; }
        public string TeamOwnerName { get; set; }
        public Nullable<System.DateTime> TeamCreateTime { get; set; }
        public Nullable<System.DateTime> TeamUpdateTime { get; set; }
    
        public virtual ICollection<MhclPlayer> MhclPlayer { get; set; }
    }
}
