//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHCL2018.Registrations.Models
{
	using System;
	using System.Collections.Generic;
	using System.ComponentModel;

	public partial class MhclTeamFullInfo
	{
		public MhclTeamFullInfo()
		{
			
		}

		[DisplayName("TEAM ID")]
		public int TeamId { get; set; }

		[DisplayName("NAME")]
		public string TeamName { get; set; }

		[DisplayName("OWNERS")]
		public string TeamOwnerName { get; set; }

		[DisplayName("PLAYERS PURCHASED")]
		public int TotalPlayerBought { get; set; }

		[DisplayName("TOTAL SPENT")]
		public int TotalPurchasePrice { get; set; }

		[DisplayName("REMAINING PURSE")]
		public int RemainingPurchasePrice { get; set; }

		[DisplayName("AVG COST FOR REMAINING PLAYERS")]
		public int AverageCostOfRemainingPlayers { get; set; }

	}
}
